### ISSUE TITLE
Linux - Python3.6 version 0.5.5 is not present

### ISSUE THREAD

**Issue by windelbouwman** [conda-forge/ppci-feedstock#2]
If you look at https://anaconda.org/conda-forge/ppci/files there is not download for python3.6 on linux64.

**Comment by windelbouwman** [comment]
@conda-forge-admin, please rerender

**Comment by isuruf** [comment]
https://circleci.com/gh/conda-forge/ppci-feedstock/9 failed due to a circleci issue. Restarting it would fix it

**Comment by isuruf** [comment]
available now

**Comment by windelbouwman** [comment]
@isuruf Nice job, thanks! Was this something I could have done myself?

**Comment by isuruf** [comment]
Yes, you should have permissions to restart a failing build in Circle-CI. If not, please let us know

**Comment by windelbouwman** [comment]
Hmm, okay. How do I do that? Just hit restart somewhere?

**Comment by isuruf** [comment]
You should see a `rerun job with SSH` button at https://circleci.com/gh/conda-forge/ppci-feedstock/9. If you press it, a new job will be started. There's no need to do it now.
